# Generated by Django 5.1.2 on 2025-09-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
